apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config

data:
  PORT: "8080"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "incident_tracker"
  DB_USER: "postgres"
  # DB_URL: "postgres://postgres:password@postgres:5432/incident_tracker?sslmode=disable"